"""init

Revision ID: dd9cf390ce1a
Revises: 
Create Date: 2023-05-08 21:29:54.129423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9cf390ce1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=34), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('inbound_client_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_client_settings_id'), 'inbound_client_settings', ['id'], unique=False)
    op.create_table('inbound_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_settings_id'), 'inbound_settings', ['id'], unique=False)
    op.create_table('jwt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('networkSettingsKey', sa.String(), nullable=True),
    sa.Column('networkSettings', sa.JSON(), nullable=True),
    sa.Column('security', sa.String(), nullable=True),
    sa.Column('securitySettingsKey', sa.String(), nullable=True),
    sa.Column('securitySettings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_settings_id'), 'stream_settings', ['id'], unique=False)
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uplink', sa.BigInteger(), nullable=True),
    sa.Column('downlink', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_id'), 'system', ['id'], unique=False)
    op.create_table('inbounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('listen', sa.String(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('stream_settings_id', sa.Integer(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.Column('client_settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_settings_id'], ['inbound_client_settings.id'], ),
    sa.ForeignKeyConstraint(['settings_id'], ['inbound_settings.id'], ),
    sa.ForeignKeyConstraint(['stream_settings_id'], ['stream_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbounds_id'), 'inbounds', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'limited', 'expired', name='clientstatus'), nullable=False),
    sa.Column('used_traffic', sa.BigInteger(), nullable=True),
    sa.Column('data_limit', sa.BigInteger(), nullable=True),
    sa.Column('data_limit_reset_strategy', sa.Enum('no_reset', 'day', 'week', 'month', 'year', name='clientdatalimitresetstrategy'), nullable=False),
    sa.Column('expire', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['inbound_id'], ['inbounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('client_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('used_traffic_at_reset', sa.BigInteger(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_usage_logs_id'), 'client_usage_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_usage_logs_id'), table_name='client_usage_logs')
    op.drop_table('client_usage_logs')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_inbounds_id'), table_name='inbounds')
    op.drop_table('inbounds')
    op.drop_index(op.f('ix_system_id'), table_name='system')
    op.drop_table('system')
    op.drop_index(op.f('ix_stream_settings_id'), table_name='stream_settings')
    op.drop_table('stream_settings')
    op.drop_table('jwt')
    op.drop_index(op.f('ix_inbound_settings_id'), table_name='inbound_settings')
    op.drop_table('inbound_settings')
    op.drop_index(op.f('ix_inbound_client_settings_id'), table_name='inbound_client_settings')
    op.drop_table('inbound_client_settings')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
