"""client-settings

Revision ID: fea0608a1598
Revises: dd9cf390ce1a
Create Date: 2023-05-08 22:09:05.647124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea0608a1598'
down_revision = 'dd9cf390ce1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'settings')
    # ### end Alembic commands ###
